apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mydb-chart.fullname" . }}-dbeaver
  labels:
    app: dbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      containers:
        - name: dbeaver
          image: {{ .Values.dbeaver.image.repository }}:{{ .Values.dbeaver.image.tag }}
          ports:
            - containerPort: 7070 # Auto-assign a port
              name: dbeaver
          volumeMounts:
            - name: dbeaver-workspace
              mountPath: /home/dbeaver/workspace
      volumes:
        - name: dbeaver-workspace
          emptyDir: {}
