apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydb-chart.fullname" . }}-dbeaver
  namespace : {{ .Values.namespace}}
  labels:
    app: dbeaver
spec:
  type: LoadBalancer
  ports:
    - port: 80 # Auto-assign a port
      targetPort: 8978
  selector:
    app: dbeaver
