apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mydb-chart.fullname" . }}-dbeaver
  namespace : {{ .Values.namespace}}
  labels:
    app: dbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      containers:
        - name: dbeaver
          image: {{ .Values.dbeaver.image.repository }}:{{ .Values.dbeaver.image.tag }}
          env:
            - name: MYSQL_HOSTNAME
              value: {{ .Values.dbeaver.mysql.hostname }}
            - name: MYSQL_DATABASE
              value: {{ .Values.dbeaver.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.dbeaver.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.dbeaver.mysql.password }}
            - name: MYSQL_PORT
              value: "{{ .Values.dbeaver.mysql.port }}"
          ports:
            - containerPort: 8978 # Auto-assign a port
              name: dbeaver
          volumeMounts:
            - name: dbeaver-workspace
              mountPath: /home/dbeaver/workspace
      volumes:
        - name: dbeaver-workspace
          emptyDir: {}
