apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydb-chart.fullname" . }}-mysql
  namespace : {{ .Values.namespace}}
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: mysql
