apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydb-chart.fullname" . }}-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  selector:
    app: mysql
