apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  grafana.ini: |-
    [paths]
    provisioning = /etc/grafana/provisioning

    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
  config.monitoring: |-
{{ .Files.Get "grafana/config.monitoring" | indent 4 }}
