apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  labels:
    app: grafana
data:
  datasource.yml: |-
{{ .Files.Get "grafana/provisioning/datasources/datasource.yml" | indent 4 }}
