apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app: grafana
data:
  datasource.yml: |-
{{ .Files.Get "grafana/provisioning/datasources/datasource.yml" | indent 4 }}
  dashboards.yml: |-
{{ .Files.Get "grafana/provisioning/dashboards/dashboard.yml" | indent 4 }}
  Docker_Prometheus_Monitoring.json: |-
{{ .Files.Get "grafana/provisioning/dashboards/Docker Prometheus Monitoring-1571332751387.json" | indent 4 }}
