apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  alert.rules: |-
{{ .Files.Get "prometheus/alert.rules" | indent 4 }}
  prometheus.yml: |-
{{ .Files.Get "prometheus/prometheus.yml" | indent 4 }}
