mysql:
  image:
    repository: mysql
    tag: 5.7
  rootPassword: admin123
  database: testdb
  user: dev
  password: admin123
  port: 3306

dbeaver:
  image:
    repository: dbeaver/cloudbeaver
    tag: latest
  workspaceVolumeSize: 1Gi
  mysql:
    hostname: mydb-chart-mysql
    database: testdb
    user: dev
    password: admin123
    port: 3306
