apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheusdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
